#!/bin/bash
# we need to remove additionalProperties from artifacts see https://github.com/massdriver-cloud/massdriver-cli/issues/64
if grep -q "\"additionalProperties\": false" $1; then
  echo "removing \"additionalProperties\" from $1 which is not allowed"
  sed -i '' '/additionalProperties"/d' $1
  exit 1
else
  exit 0
fi
