name: Build artifacts
# we dont support beta channel on artdefs yet...
on:
  pull_request:
    types: [opened, synchronized]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Massdriver CLI
        uses: dsaltares/fetch-gh-release-asset@0.0.8
        with:
          repo: "massdriver-cloud/massdriver-cli"
          file: "^mass-.*-linux-amd64\\.tar\\.gz$"
          regex: true
          token: ${{ secrets.ORGANIZATION_GITHUB_TOKEN }}

      - name: Build
        run: tar -xzf mass-*.tar.gz && export PATH=$PWD:$PATH && cd definitions/artifacts && for artifact in *.json; do echo ${artifact}; mass schema dereference ${artifact}; done
